### ISSUE TITLE
seems like graphql context does not store response object by default?

### ISSUE THREAD

**Issue by muradm** [jmcdo29/nest-cookies#1]
Example advertised causes `undefined header` error.
```
@Injectable()
export class GqlCookieInterceptor extends CookiesInterceptor {
  getRequestResponse(context: ExecutionContext) {
    const gql = GqlExecutionContext.create(context);
    return {
      req: gql.getContext().req,
      res: gql.getContext().res, // <- gql.getContext().req.res
    };
  }
}
```

May be below example would be better?
```
@Injectable()
export class GQLCookieInterceptor extends CookiesInterceptor {
  getRequestResponse(context: ExecutionContext) {
    if (context.getType() === 'http') {
      const http = context.switchToHttp()
      return { req: http.getRequest(), res: http.getResponse() }
    }

    if (context.getType<GqlContextType>() === 'graphql') {
      const gql = GqlExecutionContext.create(context)
      return { req: gql.getContext().req, res: gql.getContext().req.res }
    }

    throw new Error('Unsupported context type ' + context.getType())
  }
}
```

**Comment by jmcdo29** [comment]
What's the `context` you're providing in the `GqlModule.forRoot/Async()` configuration?

**Comment by muradm** [comment]
[repository](https://github.com/muradm/nest-cookies-context-problem/tree/master)

setting `_cookies` via normal post request or within graphql request fails with:
```
TypeError: Cannot read property '_cookies' of undefined
```
If you comment out not working and uncomment working interceptor from `app.interceptor.ts` both work.

**Comment by jmcdo29** [comment]
You don't set up the `context` for `req` and `res` to exist inside of Gql. Nest's docs [show a little of it here](https://docs.nestjs.com/techniques/authentication#graphql). You essentially need
```ts
GraphqModule.forRoot({
  context: ({ req, res }) => ({ req, res })
  // other options
})
```
in your `imports`

**Comment by muradm** [comment]
@jmcdo29, i tried that. in that case the graphql request is working, but if you post to normal service, that fails. I.e. example in README makes working one or the other.

**Comment by jmcdo29** [comment]
The example doesn't say that it will work for **all** request types. You'd need to set up some sort of check of if the request is a GQL one or a standard REST one, and return the proper values from there. Nest's `ExecutionContext` comes with the `getType()` method which can be used to determine that. It's up to the dev to know how to use and combine code.
