### ISSUE TITLE
Needs update to Nest 8

### ISSUE THREAD

**Issue by smolinari** [jmcdo29/nest-cookies#199]
Hey Jay,

I upgraded to Nest 8 and nest-cookies didn't work. It says it can't resolve the httpAdapter. I forked the repo and did a `pnpm up --latest` , rebuilt the package and linked to it locally and now the error has gone away. Not sure I should PR the changes though. 

Let me know, if I should. 

Scott

**Comment by jmcdo29** [comment]
v 1.3.0 now supports any Nest version above 7. No breaking changes between 7, 8, and 9 in terms of how the base code itself works. Sorry it took so long to get back to this
