### ISSUE TITLE
missing cookies field in cookie object causes undefined error

### ISSUE THREAD

**Issue by muradm** [jmcdo29/nest-cookies#4]
[repository](https://github.com/muradm/nest-cookies-context-problem/tree/master)

follow instructions in #1 to make interceptor working or solve #1 first :), then post to `/cookie-without-options`, you will receive `undefined error`.

**Comment by jmcdo29** [comment]
Like I said, you have the wrong `context` set up. If you want to learn more about Apollo's `context` and how to set it, I suggest [checking their docs](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#middleware-specific-context-fields). This isn't a problem in this code, or the example, but a problem in how your code is set up.

**Comment by jmcdo29** [comment]
if you have a problem after implementing the proper `context`, let's continue this on #1

**Comment by muradm** [comment]
This issue does nothing with `context` actually. It does with the fact that cookie without `options` set into `_cookies` throws `undefined`. You may see `app.controller.ts` with to requests basically different on `options` field. Same applies to cookies from graphql. source of cookie does not matter actually. on this [line](https://github.com/jmcdo29/nest-cookies/blob/dac66b82e3d05171cdc56fc77b499739c3381be3/src/cookies.interceptor.ts#L20) `options` field can be undefined.

**Comment by jmcdo29** [comment]
Ahh okay. That makes sense now. Okay, that's is definitely a bug. Should be pretty quick to add  in a `default` for the switch case that does nothing. I'll make sure to get that in for 1.2.0

**Comment by muradm** [comment]
I updated the repo, now master points to only to failing requests without `options` field in both controller and resolver.

**Comment by jmcdo29** [comment]
Version 1.2.0 is now out. This should fix the problem you were experiencing. Feel free to close it if so.

**Comment by muradm** [comment]
It didn't work. Option can't be undefined but options can.
```
          for (const [option = '', value] of Object.entries(cookie.options)) {
```
Should be:
```
          for (const [option, value] of Object.entries(cookie.options ? cookie.options : {})) {
```
Or a like.

**Comment by jmcdo29** [comment]
Ohhh, yep, I see now. You're absolutely right.

**Comment by jmcdo29** [comment]
1.2.1 published

**Comment by jmcdo29** [comment]
Seems like it's working as expected again. Feel free to reopen if it isn't
